# Generated by Django 4.2.4 on 2023-09-04 10:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0002_song_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 4, 10, 5, 37, 475046, tzinfo=datetime.timezone.utc)),
        ),
    ]
